### ISSUE TITLE
При добавление вариативного товара в корзину, добавляется лишь первая вариация.

### ISSUE THREAD

**Issue by Grollem** [karakushan/f-shop#4]
После создания вариативного товара, будь то цвета, красный ,синий, зелены, В корзину добавляется только первая вариация, с первым id. При этом цена меняется, варианты работают, но в корзине в массиве с товарами у ключа attr нет значения, оно пустое если выбрать напрмер синий(2) или зеленый(3). А если выбрать красный(1) тогда добавление происходит успешно, название меняется на заголовок вариации и ее свойство добавляется.

**Comment by Ant0ny** [comment]
Хм-м, интересная ошибка. Надо будет разобраться с ней)

**Comment by Ant0ny** [comment]
Я добавил в single.php следующий код:

fs_list_variations();

if (is_singular( array( 'product' ) ) ){
	do_action('fs_add_to_cart', $product_id = 0, $label = null, $args = array());
}

В корзину при этом добавляется только исходный товар, а не выбранная вариация.
https://yadi.sk/i/4kM8TGY1exPTwg

**Comment by Ant0ny** [comment]
Виталий, посмотри, пожалуйста, мой коммит)
