### ISSUE TITLE
При добавление одного и того же товара в корзину, создается дубль товара.

### ISSUE THREAD

**Issue by Grollem** [karakushan/f-shop#5]
При добавление одного и того же товара в корзину, создается дубль товара, вместо изменения количества, например 2, 3, добавляется еще один идентичный товар, и в корзине 2 одинаковых товара.

**Comment by Ant0ny** [comment]
Привет. Проблему я диагностировал.

https://yadi.sk/i/iely1KvWDYOlWQ
https://yadi.sk/i/CM2_7kx5tLOt4g

Ну что же. Она вполне решаема. Постараюсь решить как можно скорее.
